server:
  port: 8080

logging:
  file: logback.xml

spring:
  dataSource:
    url: jdbc:postgresql://172.16.12.11:6543/taaplc1
    username: sa
    password: tusc@6789#JKL
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      schema: db_license
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: 'SELECT 1'
