server:
  port: 8080

logging:
  file: logback.xml

spring:
  dataSource:
    url: jdbc:postgresql://127.0.0.1:6543/postgre
    username: postgre
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      schema: db_test
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: 'SELECT 1'
